# This file will contain generated by users input code that will be used in formatschedule

def are_teachers_taken(self, teachers, day_to, lesson_index):
    same_time_teachers = self.get_same_time_teacher(
        day_to=day_to,
        lesson_index=lesson_index,
    )

    for teacher in teachers:
        for same_time_teacher in same_time_teachers:
            if same_time_teacher == teacher:
                return True
    return False
