# This file will contain generated by users input code that will be used in formatschedule

def are_teachers_taken(self, teachers, day_to, lesson_index):
    same_time_teachers = self.get_same_time_teacher(
        day_to=day_to,
        lesson_index=lesson_index,
    )

    for teacher in teachers:
        for same_time_teacher in same_time_teachers:
            if same_time_teacher == teacher:
                return True
    return False

def check_teacher_conditions(teacher_id, day, days, lesson_index, teachers):
    day_index = days.index(day)
    teacher = teachers[teacher_id]
    start_index = teacher.start_hour_index[day_index]
    end_index = teacher.end_hour_index[day_index]

    if end_index == -1:
        end_index = lesson_index

    return (start_index <= lesson_index <= end_index) and teachers[teacher_id].days[day_index]
