# This file will contain generated by users input code that will be used in formatschedule

def are_teachers_taken(self, teachers, day, lesson_index, class_id, check_groups=False, group=None, log=False, log_file_name=''):
    same_time_teachers = self.get_same_time_teacher(
        day=day,
        lesson_index=lesson_index,
        class_id=class_id,
        check_groups=check_groups,
        group=group,
        log=log,
        log_file_name=log_file_name
    )

    for teacher in teachers:
        for same_time_teacher in same_time_teachers:
            if same_time_teacher == teacher:
                return True
    return False
