# Generated by Django 4.2.5 on 2024-03-18 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classrooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.TextField(default=None, null=True)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.TextField(default=None, null=True)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('possible_subjects', models.CharField(max_length=300)),
                ('start_hour_index', models.CharField(max_length=30)),
                ('end_hour_index', models.CharField(max_length=30)),
                ('days', models.CharField(max_length=30)),
                ('main_classroom_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='generatorApp.classrooms')),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generatorApp.schedulelist')),
            ],
            options={
                'unique_together': {('schedule_id', '_id')},
            },
        ),
        migrations.CreateModel(
            name='SubjectNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.TextField(default=None, null=True)),
                ('name', models.CharField(max_length=100)),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generatorApp.schedulelist')),
            ],
            options={
                'unique_together': {('schedule_id', '_id')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default={'days': ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'], 'max_lessons_per_day': 9, 'min_lessons_per_day': 5})),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generatorApp.schedulelist')),
            ],
        ),
        migrations.CreateModel(
            name='LessonHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.TextField(default=None, null=True)),
                ('start_hour', models.CharField(max_length=30)),
                ('duration', models.IntegerField()),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generatorApp.schedulelist')),
            ],
            options={
                'unique_together': {('schedule_id', '_id')},
            },
        ),
        migrations.CreateModel(
            name='ClassroomTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.TextField(default=None, null=True)),
                ('description', models.CharField(max_length=150)),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generatorApp.schedulelist')),
            ],
            options={
                'unique_together': {('schedule_id', '_id')},
            },
        ),
        migrations.AddField(
            model_name='classrooms',
            name='schedule_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generatorApp.schedulelist'),
        ),
        migrations.AddField(
            model_name='classrooms',
            name='type_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='generatorApp.classroomtypes'),
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.TextField(default=None, null=True)),
                ('grade', models.IntegerField()),
                ('class_signature', models.CharField(max_length=10)),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generatorApp.schedulelist')),
                ('starting_lesson_hour_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='generatorApp.lessonhours')),
                ('supervising_teacher_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='generatorApp.teachers')),
            ],
            options={
                'unique_together': {('schedule_id', '_id')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.TextField(default=None, null=True)),
                ('teachers_id', models.TextField(default=None, null=True)),
                ('subject_count_in_week', models.IntegerField()),
                ('number_of_groups', models.IntegerField()),
                ('max_stack', models.IntegerField()),
                ('classroom_types', models.CharField(max_length=30)),
                ('classes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generatorApp.classes')),
                ('classroom_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='generatorApp.classrooms')),
                ('lesson_hour_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='generatorApp.lessonhours')),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generatorApp.schedulelist')),
                ('subject_name_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generatorApp.subjectnames')),
            ],
            options={
                'unique_together': {('schedule_id', '_id')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='classrooms',
            unique_together={('schedule_id', '_id')},
        ),
    ]
