# Generated by Django 4.2.5 on 2024-03-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generatorApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulesettings',
            name='content',
            field=models.TextField(default='{"min_lessons_per_day": 5, "max_lessons_per_day": 9, "days": ["monday", "tuesday", "wednesday", "thursday", "friday"]}'),
        ),
    ]
