# Generated by Django 5.0 on 2024-03-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("generatorApp", "0002_alter_schedulesettings_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulelist",
            name="description",
            field=models.CharField(max_length=800, null=True),
        ),
    ]
